[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OhStem Education Wiki"
authors = [{name = "OHSTEM EDUCATION"}]
dynamic = ["version", "description"]
